### ISSUE TITLE
Loading failed for the <script>

### ISSUE THREAD

**Issue by Fzoltan87** [nao-pon/tinymceElfinder#3]
I would like to integreate a  TinyMCE+Elfinder pair for a new projekt, but it doesn't work at all.
My source code is the following between <body></body>  Tags, located at the top of my page,  JS includes looks like this:
![debug_2](https://user-images.githubusercontent.com/16391914/77919612-b0cedb80-729d-11ea-9621-1ba34fce4bf9.jpg)

The warning message is the following (Console + Network Tab):
![debug_1](https://user-images.githubusercontent.com/16391914/77919606-af9dae80-729d-11ea-9e7c-3ebb67c86ba4.jpg)

**Comment by nao-pon** [comment]
@Fzoltan87 Please move `<script>` tags inside `<head>`.

**Comment by Fzoltan87** [comment]
> 
> 
> @Fzoltan87 Please move `<script>` tags inside `<head>`.

May i ask, why this is the only solution to make the script work, please ?
Thank you for your answer.

**Comment by nao-pon** [comment]
@Fzoltan87 elFinder scans the <script> tag in <head> to find its own js directory. I have added to the README.

**Comment by Fzoltan87** [comment]
> 
> 
> @Fzoltan87 elFinder scans the <script> tag in to find its own js directory. I have added to the README.

Is there a way to change it? It would be important to me.

**Comment by nao-pon** [comment]
@Fzoltan87 Please use elFinder's option `baseUrl`. 

```javascript
const mceElf = new tinymceElfinder({
    baseUrl : './skin/elFinder/',
    // connector URL (Set your connector)
    url: 'php/connector.minimal.php',
    // upload target folder hash for this tinyMCE
    uploadTargetHash: 'l1_lw', // Hash value on elFinder of writable folder
    // elFinder dialog node id
    nodeId: 'elfinder' // Any ID you decide
});
```

**Comment by Fzoltan87** [comment]
> 
> 
> @Fzoltan87 Please use elFinder's option `baseUrl`.
> 
> ```js
> const mceElf = new tinymceElfinder({
>     baseUrl : './skin/elFinder/',
>     // connector URL (Set your connector)
>     url: 'php/connector.minimal.php',
>     // upload target folder hash for this tinyMCE
>     uploadTargetHash: 'l1_lw', // Hash value on elFinder of writable folder
>     // elFinder dialog node id
>     nodeId: 'elfinder' // Any ID you decide
> });
> ```

okay, thank you.
